export let FUTURE_VAULT_FACTORY_ENTITY = "FutureVaultFactory"
export let ASSET_ENTITY = "Asset"
export let FUTURE_ENTITY = "Future"
export let FEE_CLAIM_ENTITY = "FeeClaim"
export let USER_ENTITY = "User"
export let TRANSACTION_ENTITY = "Transaction"
