class TransactionType {
  FUTURE_VAULT_DEPOSIT: string = "FUTURE_VAULT_DEPOSIT";
  FUTURE_VAULT_WITHDRAW: string = "FUTURE_VAULT_WITHDRAW";
  AMM_ADD_LIQUIDITY: string = "AMM_ADD_LIQUIDITY";
  AMM_REMOVE_LIQUIDITY: string = "AMM_REMOVE_LIQUIDITY";
  AMM_REMOVE_LIQUIDITY_ONE: string = "AMM_REMOVE_LIQUIDITY_ONE";
  AMM_EXCHANGE: string = "AMM_EXCHANGE";
  LP_VAULT_UNDERLYING_DEPOSIT: string = "LP_VAULT_UNDERLYING_DEPOSIT";
  LP_VAULT_IBT_DEPOSIT: string = "LP_VAULT_IBT_DEPOSIT";
  LP_VAULT_WITHDRAW: string = "LP_VAULT_WITHDRAW";
  LP_VAULT_REDEEM: string = "LP_VAULT_REDEEM";
}

const transactionType = new TransactionType();
export default transactionType;
