name: Deploy subgraph
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install modules
              run: yarn
            - name: Generate config
              run: yarn generate-config:sepolia
            - name: Codegen
              run: yarn codegen:sepolia
            - name: Authorize TheGraph
              run: yarn authorize ${{secrets.THE_GRAPH_ACCESS_TOKEN}}
            - name: Deploy
              run: yarn deploy:sepolia
