name: Deploy subgraph
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Generate config
              run: yarn generate-config:goerli
            - name: Build subgraph
              run: yarn codegen && yarn build
            - name: Authorize TheGraph
              run: graph auth https://api.thegraph.com/deploy/ ${{secrets.THE_GRAPH_ACCESS_TOKEN}}
            - name: Deploy
              run: yarn deploy:goerli
